### ISSUE TITLE
USERSTORY #1: Gather General Requirements & Visual Layout

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#19]
EPIC: #1 

As a **Developer** I can **see how the site should be laid out and make a detailed plan** so that **the site functionality can be developed in an incremental manner**.

## Acceptance Criteria
* I (the developer), will understand exactly what the goals of the site/project are.
* I (the developer), will have a clear visual plan of the site's front-end and plan the user journey/stories.
* I (the developer), will understand the relationship between the database models.

## Tasks
- [x]  Set up the project Kanban Board
- [x] Write general requirements document
- [x]  Create wireframes for the front-end layout
- [x]  Create the database (DB) schema/DB structure
- [x]  Create a flow chart/logic chart
- [x]  Research Bootstrap templates
- [x]  Create the site logo
- [x]  Decide on a colour scheme
- [x]  Choose font styles
- [x]  Gather graphics, icons and images
- [x]  Write content for pages
- [x] Gather product images, descriptions and names

Story Points: 2
