### ISSUE TITLE
USERSTORY #4: View a list of products

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#22]
EPIC: #3 

As a **Shopper** I want to **view a list of products** so that **I can select something to purchase**.

## Acceptance Criteria
* As a shopper/site user, I can view a list of products

## Tasks
- [x] Create Product app
- [x] Create Product Model and Category Model
- [x] Create functionality to display the store Products from the DB
- [x] Create and connect urls
- [x] Create template for product page
- [x] Add products to the admin panel for the store
- [x] Style the Product template
- [x] Update the All Products and Shop now links to include {% url 'products' %}

Story Points: 2
