### ISSUE TITLE
USERSTORY #5: View individual product details

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#23]
EPIC: #3 

As a **Shopper** I want to **view individual product details** so that **I can identify the price, description, product rating, product image and available sizes**.

## Acceptance Criteria
* As a shopper/site user, I can view the details for a particular product (price, description, rating, image, size, etc.)
* As a shopper/site user, I can click on a link/image to take me to the product details page
* As a shopper/site user, I can view the product details to decide if I want to purchase it or not

## Tasks
- [x] Create functionality to view product detail for a particular product
- [x] Create and connect urls
- [x] Create template for product details page
- [x] Style the Product Details template
- [x] Connect with the Product Page

Story Points: 3
