### ISSUE TITLE
USERSTORY #7: View the total of my purchases

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#25]
EPIC: #3 

As a **Shopper** I want to **easily view the total of my purchases** so that **I can avoid spending too much**.

## Acceptance Criteria
* As a shopper/site user, I can see my bag total in the navbar
* As a shopper/site user, I can see my bag total when checking out
* As a shopper/site user, I can see the breakdown subtotals of my purchases in my bag/checkout

## Tasks
- [x] Add grand total functionality
- [x] Display grand total figure for bag in navigation bar (below bag icon)
- [x] Display grand total and subtotals on bag & checkout pages 

Story Points: 2
