### ISSUE TITLE
USERSTORY #8: Register for an account

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#26]
EPIC: #4 

As a **Site User** I can **easily register for an account** so that **I can have a personal account and be able to view my profile**.

## Acceptance Criteria
* As a site user, I can click on the 'register' link and register/sign up for an account.

## Tasks
- [x] Install allauth
- [x] Configure allauth settings - install allauth apps in settings.py (allauth & allauth.accounts)
- [x] Add allauth urls to project level urls.py file
- [x] Run migrations to update the DB

Story Points: 1
