### ISSUE TITLE
USERSTORY #9: Login or Logout

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#27]
EPIC: #4 

As a **Site User** I can **easily login or logout** so that **I can access my personal account information**.

## Acceptance Criteria
* As a site user, I can click the 'login' or 'logout' link to login or log out of the website.

## Tasks
- [x] Install allauth
- [x] Configure allauth settings - install allauth apps in settings.py (allauth & allauth.accounts)
- [x] Add allauth urls to project level urls.py file
- [x] Run migrations to update the DB
- [x] Update the default domain on the Admin page - in case of future use (for social media authentication)

Story Points: 1
