### ISSUE TITLE
USERSTORY #10: Recover Password

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#28]
EPIC: #4 

As a **Site User** I can **easily recover my password in case I forget it** so that **I can recover access to my account**.

## Acceptance Criteria
* As a site user, I can click 'forgot password' link to recover my password

## Tasks
- [x] Install allauth
- [x] Configure allauth settings - install allauth apps in settings.py (allauth & allauth.accounts)
- [x] Add allauth urls to project level urls.py file
- [x] Run migrations to update the DB

Story Points: 1
