### ISSUE TITLE
USERSTORY #16: Search for a product

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#34]
EPIC: #5 

As a **Shopper** I can **search for a product by name or description** so that **I can find a specific product I'd like to purchase**.

## Acceptance Criteria
* As a shopper/site user, I can search for a product using the search box in the nav bar
* As a shopper/site user, I can see the search results easily and clearly 
* As a shopper/site user, I can view a list of products that matched my search results

## Tasks
- [x] Link the search bar on the navbar to the view
- [x] Capture the search parameters and pass them to the products view
- [x] Filter and search the DB for search matches (product name + description)
- [x] Create functionality to return search results to the shopper/site user

Story Points: 3
