### ISSUE TITLE
USERSTORY #17: Search Results

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#35]
EPIC: #5 

As a **Shopper** I can **easily see what I have searched for and the number of results** so that **I can quickly decide whether the product I want is available**.

## Acceptance Criteria
* As a shopper/site user, I can search for a product using the search box in the nav bar
* As a shopper/site user, I can see the search results easily and clearly 
* As a shopper/site user, I can view a list of products that matched my search results

## Tasks
- [x] Link the search bar on the navbar to the view
- [x] Capture the search parameters and pass them to the products view
- [x] Filter and search the DB for search matches (product name + description)
- [x] Create functionality to return search results to the shopper/site user

Story Points: 2
