### ISSUE TITLE
USERSTORY #19: Select the size and quantity of a product when purchasing it

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#37]
EPIC: #6 

As a **Shopper** I can **easily select the size and quantity of a product when purchasing it** so that **I ensure that I do not accidentally select the wrong product or quantity or size**.

## Acceptance Criteria
* As a shopper/site user, I can select the size of the product (if applicable) and add it to my bag
* As a shopper/site user, I can select the quantity of the product I wish to purchase

## Tasks
- [x] Add functionality quantity of a product to the bag
- [x] Add size functionality for products
- [x] Create the front end elements on the template to handle these changes from the browser
- [x] Style the template elements

Story Points: 4
