### ISSUE TITLE
USERSTORY #20: View items in my bag to be purchased

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#38]
EPIC: #6 

As a **Shopper** I can **view items in my bag to be purchased** so that **I identify the total cost of my purchase and all items I will recieve**.

## Acceptance Criteria
* As a shopper/site user, I can add an item to my shopping bag
* As a shopper/site user, I can view items in my shopping bag
* As a shopper/site user, I can remove an item from my shopping bag

## Tasks
- [x] Create a new app Bag
- [x] Connect the app Bag to the main site urls and add it to installed apps (settings.py)
- [x] Add functionality to view the bag
- [x] Create context processor so the bag contents function is accessible throughout the project
- [x] Add functionality to add to the bag
- [x] Add functionality to remove from the bag
- [x] Create a bag template

Story Points: 3
