### ISSUE TITLE
USERSTORY #21: Adjust the quantity of individual items in my bag

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#39]
EPIC: #6 

As a **Shopper** I can **adjust the quantity of individual items in my bag** so that **I can easily make changes to my purchase before checkout**.

## Acceptance Criteria
* As a shopper/sit user, I can change the quantity or size of the product in my bag before purchasing 

## Tasks
- [x] Add functionality to increase/decrease quantity of products in the bag
- [x] Create the front end elements on the template to handle these changes from the browser
- [x] Style the template elements

Story Points: 3
