### ISSUE TITLE
USERSTORY #22: Enter payment information

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#40]
EPIC: #6 

As a **Shopper** I can **easily enter my payment information** so that **I can check out quickly and with no hassle**.

## Acceptance Criteria
* As a shopper, I can enter payment information to complete a purchase /purchase products

## Tasks
- [x] Create Checkout app and install in settings.py
- [x] Create Checkout models (Order [overall order] & OrderLineItem [product in bag])
- [x] Write methods for Order & OrderLineItem
- [x] Create Order form to collect Order data
- [x] Create Order template & view
- [x] Install Crispy forms 
- [x] Create an account on Stripe
- [x] Create element in Checkout Page/Template
- [x] Install Stripe
- [x] Add JavaScript functionality/logic to style the stripe element, show validation errors and to handle payment submit
- [x] Create env.py file to store variables/keys
- [x] Add functionality to the checkout app
- [x] Create webhooks

Story Points: 4
