### ISSUE TITLE
USERSTORY #24: View an order confirmation after checkout

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#42]
EPIC: #6 

As a **Shopper** I can **view an order confirmation after checkout** so that **I can verify that I haven't made any mistakes**.

## Acceptance Criteria
* As a shopper/site user, I want to view an order confirmation/summary after checkout

## Tasks
- [x] Create checkout success page/template
- [x] Connect checkout success urls
- [x] Add checkout success logic 
- [x] Add order summary to the success template

Story Points: 3
