### ISSUE TITLE
USERSTORY #25: Receive an email confirmation after checking out

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#43]
EPIC: #6 

As a **Shopper** I can **receive an email confirmation after checking out** so that **I can keep the confirmation of what I've purchased for my records**.

## Acceptance Criteria
* As a shopper/use, I can receive a confirmation email to confirm my purchase
* As a shopper/use, I can keep an order confirmation email for my records

## Tasks
- [x] Update webhook handler to send a confirmation email after purchase success
- [x] Make email templates
- [x] Add default from email to settings.py - print to terminal for now
- [x] Create Gmail Account for Football Crazy
- [x] Set up password appication and add to Heroku Config vars
- [x] Set up sending/receiving a real email with django - not just printing to the console

Story Points: 2
