### ISSUE TITLE
USERSTORY #26: Add a product

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#44]
EPIC: #7 

As a **Store Owner** I can **add a product** so that **I can add new items to my store**.

## Acceptance Criteria
* As a store owner/superuser, I can add a new product to my store/the website, using the front end website

## Tasks
- [x] Create function to add product
- [x] Create product form for superuser
- [x] Create template to add a product
- [x] Create urls and add link to navbar, product and product_detail
- [x] Style the templates

Story Points: 2
