### ISSUE TITLE
USERSTORY #27: Edit/update a product

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#45]
EPIC: #7 

As a **Store Owner** I can **edit/update a product** so that **I can change product prices, descriptions, images and other product criteria**.

## Acceptance Criteria
* As a store owner/superuser, I can edit a product in my store/the website, using the front end website

## Tasks
- [x] Create function to edit product
- [x] Create product form for superuser
- [x] Create template to edit a product
- [x] Create urls and add link to navbar, product and product_detail
- [x] Style the templates
- [x] Security - only for admins

Story Points: 2
