### ISSUE TITLE
USERSTORY #28: Delete a product

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#46]
EPIC: #7 

As a **Store Owner** I can **delete a product** so that **I can remove items that are no longer for sale**.

## Acceptance Criteria
* As a store owner/superuser, I can delete a product from my store/the website, using the front end website

## Tasks
- [x] Create function to delete a product
- [x] Create product form for superuser
- [x] Create modal to confirm deleting product 
- [x] Create urls and add link to navbar, product and product_detail
- [x] Style the templates
- [x] Security - only for admins

Story Points: 2
