### ISSUE TITLE
USERSTORY #29: Personalise User Profile

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#47]
EPIC: #8 

As a **Site User** I can **have a personalized user profile** so that **I can view my personal order history and order confirmations, and save my payment information**.

## Acceptance Criteria
* As a site user, I can click on the 'my profile' icon/link in the navbar to go to the My Profile page
* As a site user, I can view/update/save my delivery information on the My Profile page
* As a site user, I can view a list of my past orders/order history on the My Profile page
* As a site user, I can change my password on the My Profile page

## Tasks
- [x] Create Profiles app
- [x] Create DB model UserProfile
- [x] Create view function and connect urls
- [x] Create user profile template
- [x] Connect Navbar links - desktop and mobile
- [x] Create forms.py to handle delivery information
- [x] Update Profile to include order history info

Story Points: 8
