### ISSUE TITLE
USERSTORY #30: Customise admin area branding

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#48]
EPIC: #8 

As a **Site Admin** I can **recognise the admin area has the same look & feel as the front-end site** so that **website continuity is maintained**.

## Acceptance Criteria
* As site admin, I will see the company logo in the top left.
* As site admin, I will see familiar colours instead of the default Django colours in the admin area.

## Tasks
- [x] Install Summernote Package - rich text editor on back-end/DB 
- [x] Replace Django Admin with company logo
- [x] Change the default colours to match the front-end templates

Story Points: 0.5
