### ISSUE TITLE
USERSTORY #33: Request for contact page

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#51]
EPIC: #10 

As a **Shopper** I can **fill in a contact form** so that **I can submit a request for contact**.

## Acceptance Criteria
* Shopper/potential customer can fill in a contact form to request collaboration.

## Tasks
- [x]  Link contact to crispy form
- [x]  Import crispy form
- [x]  Create forms.py
- [x] Submit Button to submit form to the Database

Story Points: 2
