### ISSUE TITLE
USERSTORY #36: View reviews and submit a review/rating for a product

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#54]
EPIC: #11 

As a **Shopper/Site User** I want to **view product reviews and ratings** so that **I can decide whether the product is worth purchasing and gain trust in the product/store**.

## Acceptance Criteria
* As a site user, I can view product reviews and ratings

## Tasks
- [x] Create DB model
- [x] Add product review to product_detail template
- [x] Add styling to the review part of the template
- [x] Create functionality to calculate average rating score

Story Points: 5
