### ISSUE TITLE
USERSTORY #37: Modify or delete a review

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#55]
EPIC: #11 

As a **Shopper/Site User** I want to **add, modify or delete a product review** so that **I can review a product I purchased and help other shoppers to make a good choice/contribute to the site**.

## Acceptance Criteria
* As a site user, I can view product reviews and ratings
* As a registered site user, I can add a product review
* As a registered site user, I can modify/edit a product review that I wrote
* As a registered site user, I can delete a product review that I wrote

## Tasks
- [x] Create functions for updating and deleting ratings and reviews
- [x] Create template for updating and adding reviews
- [x] Create button modal for deleting reviews
- [x] Add styling to the review part of the template
- [x] Connect urls

Story Points: 4
