### ISSUE TITLE
USERSTORY #39: Create templates to handle onscreen notifications (success, error, warning and info messages)

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#57]
EPIC: #12 

As a **Shopper/Site User** I want to **get notifications when I perform an action, such as a success message** so that **I know whether my interaction/action was successful or not and that I receive feedback**.

## Acceptance Criteria
* As a Shopper/Site User, I want to receive feeback when I perform an action, such as adding a Product to my bag 
* As a Shopper/Site User, I want clear succes/error/info messages to appear when I interact with the site
* As a Shopper/Site User, I want to be able to dismiss any notifications easily

## Tasks
- [x] Create toast folder in the includes folder
- [x] Add 4 templates to the toasts folder to handle Success, Error, Info and Warning messages
- [x] Add messages (success/error/info/warning) to view function across the project

Story Points: 3
