### ISSUE TITLE
USERSTORY #40: Create Post Model for Blog

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#58]
EPIC: #13 

As a **site admin** I can **create, read, update and delete blog posts in the admin section** so that **I can manage my blog content**.

## Acceptance Criteria
* A a logged in site admin, I can create a blog post
* A a logged in site admin, I can save a draft blog post and finish it at a later time
* A a logged in site admin, I can read a blog post
* A a logged in site admin, I can update a blog post
* A a logged in site admin, I can delete a blog post
* As a front-end site user, I can see all the blog posts appear on the front end
* Given more than one post in the database, these multiple posts are listed
* Then the user sees all post titles with pagination to choose what to read

## Tasks
- [ ] Create Blog app
- [ ] Create Blog (post) model and database fields
- [ ] Create Blog details template
- [ ] Migrate database
- [ ] Create URL pattern and add URL path to project URL
- [ ] Register post model in admin.py
- [ ] Create Comment Model and Database Fields
- [ ] Register Comment model  in admin.py
- [ ] Create view methods
- [ ] Link to template
- [ ] Connect to urls.py
- [ ] Update HTML template
- [ ] Create static files
- [ ] Implement pagination to display all posts

Story Points = 4
