### ISSUE TITLE
USERSTORY #41: Display Post Detail

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#59]
EPIC: #14 

As a **Site User** I can **click on a post** so that **I can read the full text**.

## Acceptance Criteria
* As a site user, when I click on the detail button, I will be taken to a new page specific for that blog post.
* As a site user, I will see an image for the travel destination as well as the full blog text.

## Tasks
- [ ] Link the blog details button to a new view
- [ ] Display blog post data in template
- [ ] Style the blog detail template
- [ ] Add blog post to the database
- [ ] Test clicking on blog posts to view blog detail

Story Points: 2
