### ISSUE TITLE
USERSTORY #44: Write Project Documentation

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#62]
EPIC: #16 

As a **Developer** I want to **document my Django project** so that **the whole process for the ecommerce store is documented**.

## Acceptance Criteria
* Useful and meaningful documentation/README.md file
* Testing documentation

## Tasks
- [x] Introduction
- [x] UX - Planning, User Stories, Wireframes, Flowchart, Colour Scheme, Typography
- [x] Features - screenshots, code, explain
- [x] Resolved Bugs & Unresolved Bugs
- [x] Future Features/Improvements
- [x] Tools & Technologies Used
- [x] Agile Development Process
- [x] Testing.md file
- [x] Deployment
- [x] Credits
- [x] Acknowledgements

Story Points: 5
