### ISSUE TITLE
USERSTORY #45: Final Deployment

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#63]
EPIC: #17 

As a **Developer** I want to **deploy my project/website** so that **it can be accessed publicly online**.

## Acceptance Criteria
* As a developer, I can deploy the project to Heroku
* As a site user, I can access the project on Heroku, using the URL

## Tasks
- [ ] Create Heroku project/app
- [ ] Deploy initial project
- [ ] Fix any deployment bugs, if present
- [ ] Create SQL Database - Elephant SQL
- [ ] Connect your db to your local development web server
- [ ] Create secret keys
- [ ] Ensure all keys are kept secret
- [ ] Create AWS Account 
- [ ] Create AWS Groups, Policies and Users
- [ ] Ensure Amazon AWS connected for images - Connect Django to S3
- [ ] Complete - Caching, Media Files & Stripe
