### ISSUE TITLE
USER STORY: #47: Wishlist

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#66]
EPIC: #

As a **Shopper/site user** I want to **be able to add and view products to a wish list** so that **I can save products I would wish to purchase in the future**.

## Acceptance Criteria
* As a shopper/site user, I can click a button to easily add a product to my wishlist
* As a shopper/site user, I can view my wishlist
* As a shopper/site user, I can remove a product from my wishlist

## Tasks
- [x] Add wishlist field to the UserProfile model & migrate
- [x] Create the Views (function) to allow users to add products to their wishlist and store wishlist data in the DB
- [x] Create the font-end elements for wishlist (template in My Profile) and buttons to add to wishlist
- [x] Add to UserProfile template so User can view Items in their wishlist 
- [x] Add functionality to remove item from wishlist
