### ISSUE TITLE
USER STORY: #48 Newsletter

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#67]
EPIC: #

As a **site user** I want to **subscribe to the newsletter** so that **I keep up to date with the latest store news and deals**.

## Acceptance Criteria
* As a site user, I can subscribe to the newsletter
* As a site user, I can unsubscribe from the newsletter
* As a site user, I can receive newsletter emails

## Tasks
- [x] Create newsletter app
- [x] Connect urls and project level urls
- [x] Create model >> connect to backend DB
- [x] Write views/functionality to allow users to subscribe and unsubscribe from the newsletter
- [x] Create the font-end elements for subscribing/unsubscribing
- [x] Create view, url, form and template to allow admin to send newsletter email from the website front-end (accessed through my profile)
