### ISSUE TITLE
USER STORY: #49 Create Comment Model

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#68]
EPIC: #14 

As a **Site Admin** I can **create Comments table/model** so that **I can manage comments**.

## Acceptance Criteria
* As site admin, I can log in to the Django admin area and create a new comment.

## Tasks
- [ ] Create Comment model in Blog app
- [ ] Create database fields for Comment
- [ ] Migrate database
- [ ] Register model in admin.py
- [ ] Add some Comment data to test

Story Points = 1
