### ISSUE TITLE
USER STORY: #51 Modify or delete Comment on a Post

### ISSUE THREAD

**Issue by roc-11** [roc-11/football-crazy-pp5#70]
EPIC: #14

As a **Site User** I can **modify or delete my comment on a post** so that **I can be involved in the conversation**.

## Acceptance Criteria
* Given a logged in site user, they can modify their comment.
* Given a logged in user, they can delete their comment

## Tasks
- [ ] Create Edit Button and Delete Button
- [ ] Link edit button to edit comment template
- [ ] Prepopulate comment text field when edit button clicked (with DB data)
- [ ] Update Comment button submits changes to DB
- [ ] Status reverts to pending (approved by Site Admin)
- [ ] Link Delete Button to Bootstrap Modal - defensive programming
- [ ] "Are you sure you want to delete?" modal appears before user can delete comment
- [ ] Delete button then removes DB comment

Story Points = 3
